version: '3.8'

services:
  userbot:
    build: .
    container_name: pyrogram-userbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./userbot.session:/app/userbot.session
      - ./logs:/app/logs
    tty: true
    stdin_open: true